In [1]:
import numpy as np
from itertools import combinations

In [2]:
fNames = ["input", "test"]
with open(fNames[0]) as a:
    input = [list(l.strip("\n")) for l in a.readlines()]

surface_org = np.array(input)
len(input), surface_org

(140,
 array([['.', '.', '.', ..., '.', '.', '.'],
        ['.', '.', '.', ..., '.', '.', '.'],
        ['.', '.', '.', ..., '.', '.', '.'],
        ...,
        ['.', '.', '.', ..., '.', '.', '.'],
        ['.', '.', '.', ..., '.', '.', '.'],
        ['.', '.', '.', ..., '.', '.', '.']], dtype='<U1'))

In [3]:
def expand(matrix: np.ndarray):
    res = matrix.copy()
    # indexes_row, indexes_row =
    indexes_row, indexes_col = get_expansion_indexes(matrix)
    print(indexes_row, indexes_col)
    # print(indexes.ravel())
    for ix in reversed(indexes_row.ravel()):
        res = np.insert(res, ix, "*", axis=0)
    for ix in reversed(indexes_col.ravel()):
        res = np.insert(res, ix, "*", axis=1)
    return res


def get_expansion_indexes(matrix):
    indexes_row = np.argwhere((matrix == ".").sum(axis=1) == matrix.shape[0]).ravel()
    indexes_col = np.argwhere((matrix == ".").sum(axis=0) == matrix.shape[1]).ravel()
    return indexes_row, indexes_col


get_expansion_indexes(surface_org)

(array([ 47,  75,  85,  89, 121]), array([ 20,  24,  37,  79,  83, 129]))

In [4]:
surface = expand(surface_org)
print(surface.shape)
print(surface)

[ 47  75  85  89 121] [ 20  24  37  79  83 129]
(145, 146)
[['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']
 ...
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']]


In [5]:
galaxies = np.argwhere(surface == "#")

In [6]:
ix_pair = list(combinations(range(len(galaxies)), 2))
len(ix_pair)

98790

In [7]:
def get_distance(a: np.ndarray, b: np.ndarray):
    return sum(np.abs(a - b))


def get_all_distances(coord):
    [f, t] = coord
    # print(coord, indexes_col[f],indexes_col[t])
    return get_distance(galaxies[f], galaxies[t])


sum(list(map(get_all_distances, ix_pair)))

9742154

## Part 2


In [8]:
indexes_row, indexes_col = get_expansion_indexes(surface_org)
galaxies = np.argwhere(surface_org == "#")
ix_pair = list(combinations(range(len(galaxies)), 2))
len(ix_pair)
print(indexes_row, indexes_col)

[ 47  75  85  89 121] [ 20  24  37  79  83 129]


In [9]:
def crosses(a: int, b: int, indexes: np.ndarray):
    min_val = min(a, b)
    max_val = max(a, b)
    return (min_val < indexes) & (indexes < max_val)


def get_distance(a: np.ndarray, b: np.ndarray):
    mul = 10**6 - 1
    std_sum = sum(np.abs(a - b))
    f_row, f_col = a
    t_row, t_col = b
    row = crosses(f_row, t_row, indexes_row)
    col = crosses(f_col, t_col, indexes_col)
    return std_sum + (mul * sum(row)) + (mul * sum(col))

In [10]:
sum(list(map(get_all_distances, ix_pair)))

411142919886