# day four

In [207]:
import numpy as np

## Part 1

In [217]:
filename = "test"
# filename = "input"
def get_data(filename):
    with open(filename) as f:
        numbers = f.readline().strip().split(",")
        numbers = np.array(numbers, dtype="int8")
        grids = [ln.strip().replace("  ", " ").split(" ") for ln in f.readlines()]
        grids = [ln for ln in grids if len(ln) > 1]
        grids = np.matrix(grids, dtype="int8")
        grids = np.split(grids, len(grids) // 5)
        return numbers, grids


numbers, grids = get_data(filename)


In [218]:
def isBingo(grid, selectedNumber):
    if len(selectedNumber) < 5:
        return False
    # check cols
    for iy in range(5):   
        matches = 0 
        for num in selectedNumber:
            matches += num in grid[:,iy]
            if matches >= 5:
                return True

    #check rows
    for ix in range(5):   
        matches = 0 
        for num in selectedNumber:
            matches += num in grid[ix,:]
            if matches >= 5:
                return True
        
print(grids[2])
isBingo(grids[2], [7,4,9,5,11,17,23,2,0,14,21,24])


[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]


True

In [219]:
grids[-1]

matrix([[14, 21, 17, 24,  4],
        [10, 16, 15,  9, 19],
        [18,  8, 23, 26, 20],
        [22, 11, 13,  6,  5],
        [ 2,  0, 12,  3,  7]], dtype=int8)

In [220]:
selectedNumber = []
try: 
    for num in numbers:
        selectedNumber.append(num)
        # print(selectedNumber)
        for grid in grids:
            if (isBingo(grid, selectedNumber)):
                print(f"{selectedNumber = }")
                print(f"{sum(selectedNumber) = }")
                print(grid)
                raise StopIteration

except StopIteration as si:
    pass
finally:
    print("done")


selectedNumber = [7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24]
sum(selectedNumber) = 137
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
done


well it seems like I missed the part that the sum is going be the unmarked numbers,
so I had calc the val manually. 

And I made the solution allot harder the it should have been. 

In [221]:
sum([34, 81, 75, 42, 27, 59, 20, 87, 45, 46, 23, 76, 40, 25, 96, 53]) * 17

14093

## Part 2
what we need to is to pop each bingo card out til we get one card remaining.

### Retrying part 1
because I misunderstood the validation and task of part 2 I think will remake the part one agin   

In [222]:
def find_and_replace_value(grid, value, newvalue):
    if (value in grid):
        x, y = np.where(grid == value)
        grid[x,y] = newvalue

def is_bingo(grid):
    for ix in range(5):
        if np.sum(grid[ix,:]) <= -5:
            return True
    for iy in range(5):
        if np.sum(grid[:,iy]) <= -5:
            return True
    return False


In [223]:
is_bingo(grids[2])

False

In [224]:
print(grid)
find_and_replace_value(grid, -1, 0)
print(grid)
np.sum(grid)

[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]


325

In [229]:
# numbers, grids = get_data("test")
numbers, grids = get_data("input")


In [230]:
try:
    for i in numbers:
        for grid in grids:
            find_and_replace_value(grid, i, -1)
            if is_bingo(grid):
                print("BINGO!!!")
                print(grid)
                find_and_replace_value(grid, -1, 0)
                print("Ans: ",np.sum(grid)* i)
                raise StopIteration
except StopIteration:
    print("done")


BINGO!!!
[[34 -1 81 75 42]
 [27 -1 59 20 87]
 [45 -1 46 23 76]
 [40 -1 -1 25 96]
 [-1 -1 -1 53 -1]]
Ans:  14093
done


### part 2

In [334]:
# numbers, grids = get_data("test")
numbers, grids = get_data("input")


In [343]:
numbers, grids = get_data("input")
bingo_ix = -1
try:
    for i in numbers:
        if bingo_ix >= 0:
            ## clear all invalid bingos
            for ix, grid in reversed(list(enumerate(grids))):
                x,y = np.where(grids == 0)
                if len(x) >= 5:
                    grids.pop(ix)

            bingo_ix = -1

        # print(len(grids))
        for ix, grid in enumerate(grids):
            find_and_replace_value(grid, i, -1)
            if is_bingo(grid):
                # print("BINGO!!!")
                # print(grid)
                find_and_replace_value(grid, -1, 0)
                # print("Ans: ",np.sum(grid)* i)
                bingo_ix = ix
                print(ix)
                # raise StopIteration
except StopIteration:
    print("done")
# grids

100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
40
99
99
99
99
99
17
98
98
98
47
97
97
97
97
97
97
97
79
80
96
72
95
95
95
41
94
94
26
93
55
68
92
22
91
18
43
90
23
72
89
73
88
15
82
87
5
45
86
38
85
6
56
84
21
75
83
83
4
81
82
27
36
56
81
7
47
80
8
13
44
79
14
24
26
53
63
76
78
2
77
1
44
68
76
11
32
33
37
43
75
42
59
67
69
70
74
15
24
28
34
48
73
67
72
2
8
44
68
71
71
16
31
48
53
65
70
39
56
64
69
55
61
68
51
61
67
40
59
65
66
66
9
18
65
29
51
64
45
59
63
63
10
37
62
18
28
54
61
61
61
20
51
60
60
0
43
59
35
58
26
57
57
44
56
56
56
56
56
56
56
56
56
19
55
55
43
54
54
54
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
53
53


In [349]:
np.where(grids[0] == 0)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4,
        4, 4]),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 4, 0, 1, 2, 3, 4, 0, 1, 2,
        3, 4]))