# day four

In [207]:
import numpy as np

## Part 1

In [217]:
filename = "test"
# filename = "input"
def get_data(filename):
    with open(filename) as f:
        numbers = f.readline().strip().split(",")
        numbers = np.array(numbers, dtype="int8")
        grids = [ln.strip().replace("  ", " ").split(" ") for ln in f.readlines()]
        grids = [ln for ln in grids if len(ln) > 1]
        grids = np.matrix(grids, dtype="int8")
        grids = np.split(grids, len(grids) // 5)
        return numbers, grids


numbers, grids = get_data(filename)


In [218]:
def isBingo(grid, selectedNumber):
    if len(selectedNumber) < 5:
        return False
    # check cols
    for iy in range(5):   
        matches = 0 
        for num in selectedNumber:
            matches += num in grid[:,iy]
            if matches >= 5:
                return True

    #check rows
    for ix in range(5):   
        matches = 0 
        for num in selectedNumber:
            matches += num in grid[ix,:]
            if matches >= 5:
                return True
        
print(grids[2])
isBingo(grids[2], [7,4,9,5,11,17,23,2,0,14,21,24])


[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]


True

In [219]:
grids[-1]

matrix([[14, 21, 17, 24,  4],
        [10, 16, 15,  9, 19],
        [18,  8, 23, 26, 20],
        [22, 11, 13,  6,  5],
        [ 2,  0, 12,  3,  7]], dtype=int8)

In [220]:
selectedNumber = []
try: 
    for num in numbers:
        selectedNumber.append(num)
        # print(selectedNumber)
        for grid in grids:
            if (isBingo(grid, selectedNumber)):
                print(f"{selectedNumber = }")
                print(f"{sum(selectedNumber) = }")
                print(grid)
                raise StopIteration

except StopIteration as si:
    pass
finally:
    print("done")


selectedNumber = [7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24]
sum(selectedNumber) = 137
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
done


well it seems like I missed the part that the sum is going be the unmarked numbers,
so I had calc the val manually. 

And I made the solution allot harder the it should have been. 

In [221]:
sum([34, 81, 75, 42, 27, 59, 20, 87, 45, 46, 23, 76, 40, 25, 96, 53]) * 17

14093

## Part 2
what we need to is to pop each bingo card out til we get one card remaining.

### Retrying part 1
because I misunderstood the validation and task of part 2 I think will remake the part one agin   

In [222]:
def find_and_replace_value(grid, value, newvalue):
    if (value in grid):
        x, y = np.where(grid == value)
        grid[x,y] = newvalue

def is_bingo(grid):
    for ix in range(5):
        if np.sum(grid[ix,:]) <= -5:
            return True
    for iy in range(5):
        if np.sum(grid[:,iy]) <= -5:
            return True
    return False


In [223]:
is_bingo(grids[2])

False

In [229]:
# numbers, grids = get_data("test")
numbers, grids = get_data("input")


In [230]:
try:
    for i in numbers:
        for grid in grids:
            find_and_replace_value(grid, i, -1)
            if is_bingo(grid):
                print("BINGO!!!")
                print(grid)
                find_and_replace_value(grid, -1, 0)
                print("Ans: ",np.sum(grid)* i)
                raise StopIteration
except StopIteration:
    print("done")


BINGO!!!
[[34 -1 81 75 42]
 [27 -1 59 20 87]
 [45 -1 46 23 76]
 [40 -1 -1 25 96]
 [-1 -1 -1 53 -1]]
Ans:  14093
done


### part 2

In [334]:
# numbers, grids = get_data("test")
numbers, grids = get_data("input")


In [362]:
numbers, grids = get_data("input")
bingo_ix = -1
try:
    for i in numbers:
        if bingo_ix >= 0:
            ## clear all invalid bingos
            for ix, grid in reversed(list(enumerate(grids))):
                x,y = np.where(grid == 0)
                if len(x) >= 5:
                    grids.pop(ix)

            bingo_ix = -1

        # print(len(grids))
        for ix, grid in enumerate(grids):
            find_and_replace_value(grid, i, -1)
            if is_bingo(grid):
                print("BINGO!!!")
                print(grid)
                find_and_replace_value(grid, -1, 0)
                print(i)
                print("Ans: ",np.sum(grid)* i)
                bingo_ix = ix
                # raise StopIteration
except StopIteration:
    print("done")
# grids

BINGO!!!
[[34 -1 81 75 42]
 [27 -1 59 20 87]
 [45 -1 46 23 76]
 [40 -1 -1 25 96]
 [-1 -1 -1 53 -1]]
17
Ans:  14093
BINGO!!!
[[-1 -1 44 -1 91]
 [78 -1 -1 -1 31]
 [89 41 94 -1 -1]
 [58 23 -1 -1 16]
 [24 -1 80 -1 -1]]
53
Ans:  35457
BINGO!!!
[[-1 -1 -1 -1 -1]
 [26 25 49 61 -1]
 [-1 73 75 47 19]
 [ 9 95 -1 46 98]
 [86 -1 35 81 -1]]
60
Ans:  49500
BINGO!!!
[[26 70 -1  5 89]
 [94 49 35 -1 99]
 [82 36 -1 78 37]
 [90 73  9 -1 40]
 [-1 -1 -1 -1 -1]]
60
Ans:  54720
BINGO!!!
[[-1 -1 -1 -1 -1]
 [-1 -1 49 -1 -1]
 [87 -1 27 26 -1]
 [19  9 45 98 76]
 [85 80  5  7 25]]
65
Ans:  41470
BINGO!!!
[[-1 -1 -1 -1 -1]
 [70 71 -1 35 13]
 [91  6 47 -1 -1]
 [15 76 59 74 -1]
 [46 80 95 27 -1]]
65
Ans:  52325
BINGO!!!
[[47 -1 58 98 59]
 [-1 49 -1 81 -1]
 [-1 -1 -1 -1 -1]
 [-1 95 27 74 22]
 [-1 45 -1 44 33]]
34
Ans:  24888
BINGO!!!
[[-1 91 55 76 74]
 [-1 -1 59 58 44]
 [99 29 -1 -1 87]
 [-1 -1 -1 -1 -1]
 [90 13 82 -1 78]]
42
Ans:  39270
BINGO!!!
[[-1 94 -1 -1 -1]
 [-1 80 -1 89 -1]
 [-1 -1 74 52  5]
 [-1 69 -1 -1 81]

In [359]:
# np.where(grids[0] == 0)
len(grids)

0