# [day 13](https://adventofcode.com/2023/day/13)

In [1]:
import numpy as np

In [2]:
def segment_to_image(segment: str):
  rows = segment.split('\n')
  arr = np.array([list(r) for r in rows])
  ret = np.zeros(arr.shape, dtype=np.int8)
  ret[arr == '#'] = 1
  return ret

In [3]:
fNames = ["input", "test"]
with open(fNames[0]) as a:
    raw = a.read()
    input = [segment_to_image(l.strip("\n")) for l in raw.split('\n\n')]

len(input)

100

In [4]:
input[0].shape

(7, 11)

In [5]:
sel = input[0].T
print(sel[4])
print(sel[5])
np.all(sel[4] == sel[5])


[1 1 1 0 1 1 0]
[1 1 0 0 0 0 0]


False

In [6]:
print(sel[:5])
print('------------')
print(sel[5:])
# l[:5] == l[5:]
print(sel[:5].shape, sel[5:].shape, len(sel[5:]))

[[1 1 0 0 0 0 0]
 [1 1 1 0 1 1 0]
 [0 1 1 0 1 1 1]
 [0 1 1 0 1 1 1]
 [1 1 1 0 1 1 0]]
------------
[[1 1 0 0 0 0 0]
 [0 0 1 0 1 0 1]
 [0 0 1 0 1 0 1]
 [1 1 0 0 0 0 0]
 [1 1 1 0 1 1 0]
 [0 1 1 1 1 1 1]]
(5, 7) (6, 7) 6


In [7]:
sel[:4]

array([[1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 1, 1, 0],
       [0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 1]], dtype=int8)

In [8]:
def fold_n_cut(arr: np.ndarray, at: int):
    fold_ix = at + 1
    len_left = len(arr[:fold_ix])
    len_right = len(arr[fold_ix:])
    len_min = min(len_left, len_right)
    if len_left < len_right:
        left = arr[:fold_ix]
        right = arr[fold_ix : fold_ix + len_min]
        return left, right
    else:
        left = arr[fold_ix - len_min : fold_ix]
        right = arr[fold_ix:]
        return left, right


def flip_n_test(left: np.ndarray, right: np.ndarray):
    return np.all(left == np.flip(right, axis=0))


flip_n_test(*fold_n_cut(input[0], 4))

False

In [9]:
fold_n_cut(input[0], 4)

(array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1]], dtype=int8),
 array([[0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1],
        [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1]], dtype=int8))

In [10]:
def find_fold_index(arr:np.ndarray, rows=True):
  for ix in range(len(arr)-1):
    test = flip_n_test(*fold_n_cut(arr, ix))
    if test:
      return rows, ix + 1
  if rows:
    return find_fold_index(arr.T, rows=False)
  return None, None
    
find_fold_index(input[0]), find_fold_index(input[1])

((False, 3), (True, 10))

In [11]:
def get_summarize(value: int, mul:bool):
  if (value == None): 
    return 0
  if (mul): 
    return value * 100
  return value

In [12]:
vals = [get_summarize(i,m) for m, i in map(find_fold_index, input)]
sum(vals)

34993

## Part 2

In [13]:
def flip_n_test(left: np.ndarray, right: np.ndarray):
    return np.sum(~(left == np.flip(right, axis=0))) == 1


In [14]:
vals = [get_summarize(i,m) for m, i in map(find_fold_index, input)]
sum(vals)

29341